{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.scimall",
    "module": "imsdk",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.netease.yunxin.kit.contact",
          "module": "contactkit-ui",
          "version": {
            "requires": "9.3.0"
          }
        },
        {
          "group": "com.netease.yunxin.kit.conversation",
          "module": "conversationkit-ui",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "com.netease.yunxin.kit.team",
          "module": "teamkit-ui",
          "version": {
            "requires": "9.3.0"
          }
        },
        {
          "group": "com.netease.yunxin.kit.chat",
          "module": "chatkit-ui",
          "version": {
            "requires": "9.3.0"
          }
        },
        {
          "group": "com.netease.yunxin.kit.search",
          "module": "searchkit-ui",
          "version": {
            "requires": "9.3.0"
          }
        },
        {
          "group": "com.netease.yunxin.kit.locationkit",
          "module": "locationkit",
          "version": {
            "requires": "9.3.0"
          }
        },
        {
          "group": "com.netease.yunxin.kit.common",
          "module": "common-ui",
          "version": {
            "requires": "1.1.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "imsdk-1.0.2.aar",
          "url": "imsdk-1.0.2.aar",
          "size": 154104,
          "sha512": "9994143cd3d5433ea26efd008a51ef4cc3378a27476ce8120fc187fe9a75207e82cd31d8737fb511bb4da1117858f9e00dbad71b4e6d1e6a3cc808f211fec599",
          "sha256": "6472eb5296e4a1feae41dbca3c6ffb2690936464e08f58ed77eb0151b697f4b3",
          "sha1": "4ca789b8fb33372973a3ceac709eeeb6bb578a64",
          "md5": "ef1ffea8f9b6db78829b5aca1ab35939"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.13.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.12"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.netease.yunxin.kit.contact",
          "module": "contactkit-ui",
          "version": {
            "requires": "9.3.0"
          }
        },
        {
          "group": "com.netease.yunxin.kit.conversation",
          "module": "conversationkit-ui",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "com.netease.yunxin.kit.team",
          "module": "teamkit-ui",
          "version": {
            "requires": "9.3.0"
          }
        },
        {
          "group": "com.netease.yunxin.kit.chat",
          "module": "chatkit-ui",
          "version": {
            "requires": "9.3.0"
          }
        },
        {
          "group": "com.netease.yunxin.kit.search",
          "module": "searchkit-ui",
          "version": {
            "requires": "9.3.0"
          }
        },
        {
          "group": "com.netease.yunxin.kit.locationkit",
          "module": "locationkit",
          "version": {
            "requires": "9.3.0"
          }
        },
        {
          "group": "com.netease.yunxin.kit.common",
          "module": "common-ui",
          "version": {
            "requires": "1.1.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "imsdk-1.0.2.aar",
          "url": "imsdk-1.0.2.aar",
          "size": 154104,
          "sha512": "9994143cd3d5433ea26efd008a51ef4cc3378a27476ce8120fc187fe9a75207e82cd31d8737fb511bb4da1117858f9e00dbad71b4e6d1e6a3cc808f211fec599",
          "sha256": "6472eb5296e4a1feae41dbca3c6ffb2690936464e08f58ed77eb0151b697f4b3",
          "sha1": "4ca789b8fb33372973a3ceac709eeeb6bb578a64",
          "md5": "ef1ffea8f9b6db78829b5aca1ab35939"
        }
      ]
    }
  ]
}
